# 📘 LU Decomposition

## ✅ What is LU Decomposition?

LU Decomposition is the factorization of a **square matrix** $A \in \mathbb{R}^{n \times n}$ into the product:

$$
A = LU
$$

Where:
- $L$ is a **lower triangular matrix** with ones on the diagonal  
- $U$ is an **upper triangular matrix**

## 🧪 When Does LU Decomposition Exist?

- LU decomposition **without pivoting** exists if the matrix allows Gaussian elimination without row swaps  
- LU **with pivoting** always exists, and is usually expressed as:

$$
PA = LU
$$

Where $P$ is a **permutation matrix**

## 🔧 How It Works (No Pivoting)

The process is based on **Gaussian elimination**:
- Eliminate entries below the diagonal  
- Store the multipliers in $L$  
- The resulting upper matrix is $U$

## 🧮 Example

Let:

$$
A = \begin{bmatrix}
2 & 3 \\
4 & 7
\end{bmatrix}
$$

We find:

$$
L = \begin{bmatrix}
1 & 0 \\
2 & 1
\end{bmatrix}, \quad
U = \begin{bmatrix}
2 & 3 \\
0 & 1
\end{bmatrix}
$$

Because:

$$
LU = \begin{bmatrix}
1 & 0 \\
2 & 1
\end{bmatrix}
\begin{bmatrix}
2 & 3 \\
0 & 1
\end{bmatrix}
=
\begin{bmatrix}
2 & 3 \\
4 & 7
\end{bmatrix} = A
$$

## 🔁 Applications in Numerical Linear Algebra

- Solving systems of equations $Ax = b$:
  - Step 1: Solve $Ly = b$
  - Step 2: Solve $Ux = y$
- Computing matrix inverses efficiently  
- Determinant computation: $\det(A) = \det(L) \cdot \det(U)$  
- Foundation for more advanced factorizations (e.g., Crout’s, Doolittle’s, pivoted LU)

## ✅ Summary

- LU Decomposition expresses $A = LU$ with triangular matrices  
- Simplifies solving systems, inverses, and modeling equations  
- Widely used in numerical analysis, optimization, and finance


## Implementation from Scratch

In [4]:
import numpy as np

def lu_decomposition(A):
    """
    Performs LU Decomposition of a square matrix A without pivoting.
    Returns L and U such that A = LU.
    Assumes A is square and decomposition is possible without row exchanges.
    """
    n = A.shape[0]
    L = np.zeros_like(A, dtype=float)
    U = np.zeros_like(A, dtype=float)

    for i in range(n):
        # Compute U row
        for j in range(i, n):
            U[i, j] = A[i, j] - sum(L[i, k] * U[k, j] for k in range(i))

        # Compute L column
        L[i, i] = 1  # unit diagonal
        for j in range(i+1, n):
            L[j, i] = (A[j, i] - sum(L[j, k] * U[k, i] for k in range(i))) / U[i, i]

    return L, U

In [5]:
def forward_substitution(L, b):
    """
    Solves L y = b for y using forward substitution.
    """
    n = L.shape[0]
    y = np.zeros(n)
    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])
    return y

In [6]:
def backward_substitution(U, y):
    """
    Solves U x = y for x using backward substitution.
    """
    n = U.shape[0]
    x = np.zeros(n)
    for i in reversed(range(n)):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]
    return x

In [7]:
def lu_test_example(A, b):
    L, U = lu_decomposition(A)

    print("Matrix A:")
    print(A)
    print("\nLower Triangular Matrix L:")
    print(L)
    print("\nUpper Triangular Matrix U:")
    print(U)
    
    # Verify A = LU
    A_reconstructed = L @ U
    print("\nReconstructed A (L @ U):")
    print(A_reconstructed)

    # Compute Reconstruction Error
    print("\nReconstruction Error:", np.linalg.norm(A - A_reconstructed))
    
    # Solve Ax = b
    y = forward_substitution(L, b)
    x = backward_substitution(U, y)
    print("\nSolution x to Ax = b:")
    print(x)
    
    # Verify solution
    print("\nCheck Ax:")
    print(A @ x)

    # Compute solution error
    b_hat = A @ x
    sol_error = np.linalg.norm(b - b_hat)
    print("Solution Accuracy (‖Ax - b‖):", sol_error)

## Examples

### Example 1

In [10]:
# Example usage
A_1 = np.array([[2.0, 3.0],
              [4.0, 7.0]])

b_1 = np.array([5.0, 13.0])

In [11]:
lu_test_example(A_1, b_1)

Matrix A:
[[2. 3.]
 [4. 7.]]

Lower Triangular Matrix L:
[[1. 0.]
 [2. 1.]]

Upper Triangular Matrix U:
[[2. 3.]
 [0. 1.]]

Reconstructed A (L @ U):
[[2. 3.]
 [4. 7.]]

Reconstruction Error: 0.0

Solution x to Ax = b:
[-2.  3.]

Check Ax:
[ 5. 13.]
Solution Accuracy (‖Ax - b‖): 0.0


### Example 2

In [13]:
A_2 = np.array([[4.0, 3.0],
               [6.0, 3.0]])
b_2 = np.array([10.0, 12.0])

In [14]:
lu_test_example(A_2, b_2)

Matrix A:
[[4. 3.]
 [6. 3.]]

Lower Triangular Matrix L:
[[1.  0. ]
 [1.5 1. ]]

Upper Triangular Matrix U:
[[ 4.   3. ]
 [ 0.  -1.5]]

Reconstructed A (L @ U):
[[4. 3.]
 [6. 3.]]

Reconstruction Error: 0.0

Solution x to Ax = b:
[1. 2.]

Check Ax:
[10. 12.]
Solution Accuracy (‖Ax - b‖): 0.0


### Example 3

In [16]:
A_3 = np.array([[1.0, 2.0, 4.0],
               [3.0, 8.0, 14.0],
               [2.0, 6.0, 13.0]])
b_3 = np.array([3.0, 13.0, 17.0])

In [17]:
lu_test_example(A_3, b_3)

Matrix A:
[[ 1.  2.  4.]
 [ 3.  8. 14.]
 [ 2.  6. 13.]]

Lower Triangular Matrix L:
[[1. 0. 0.]
 [3. 1. 0.]
 [2. 1. 1.]]

Upper Triangular Matrix U:
[[1. 2. 4.]
 [0. 2. 2.]
 [0. 0. 3.]]

Reconstructed A (L @ U):
[[ 1.  2.  4.]
 [ 3.  8. 14.]
 [ 2.  6. 13.]]

Reconstruction Error: 0.0

Solution x to Ax = b:
[-5.66666667 -0.33333333  2.33333333]

Check Ax:
[ 3. 13. 17.]
Solution Accuracy (‖Ax - b‖): 3.66205343881779e-15


## 💹 Applications in Quantitative Finance

LU decomposition is useful in many financial applications:

### 1. Risk Modeling
- Portfolio variance: $\sigma^2 = w^T \Sigma w$
- LU decomposition is used to solve $\Sigma x = w$

### 2. Portfolio Optimization
- In Mean-Variance Optimization:
  $$
  \Sigma x = \mu
  $$
- LU makes solving this efficient and stable

### 3. Factor Models
- Fitting models like $R = Bf + e$
- LU helps invert or solve systems involving $B$ or $B^T B$

### 4. Simulation Engines
- Used in Monte Carlo simulations to apply correlation
- Solve linear constraints efficiently